### ISSUE TITLE
Odd resolution scaling

### ISSUE THREAD

**Issue by FreshRoyal** [HFTSRedux/TS2Redux#10]
I'm having odd resolution scaling issues. I'm using a 1920x1080 display at 60 hz with Windows' resolution scaling set to 100%.

![image](https://user-images.githubusercontent.com/77604559/147425622-1ceb8316-1731-4865-a36e-1f78320c9c72.png)

**Comment by GoTeamScotch** [comment]
Make sure your video settings are set correctly in Homefront's settings menu here: Main Menu > Options > Graphics.
1. Make sure resolution is set to 1920x1080 (or smaller)
2. Disable supersampling (found under _Advanced Graphics_). Set it to "1x (off)".

Alternatively, you can change these settings in manually. Press Windows Key + R, then paste this into the Run window that appears:
`notepad %UserProfile%\Saved Games\homefront2\game.cfg`

Focus on these settings:
- r_Height = 1080
- r_Width = 1920
- r_supersampling = 1

**Comment by GoTeamScotch** [comment]
The new installer that was just released should address this issue as part of the installation process. It will check your game config file and update the supersampling option (to disable it).

You can either use my suggestion above, or use the new installer:
[TS2 Redux v0.2.6](https://github.com/HFTSRedux/TS2Redux/releases/tag/v0.2.6)

Marking this issue as resolved. Feel free to reply still if you continue to encounter this problem.
