### ISSUE TITLE
Installer: TS2 Launcher creator doesn't work with spaced-paths

### ISSUE THREAD

**Issue by GoTeamScotch** [HFTSRedux/TS2Redux#2]
Reported via Discord.

Users with spaces in their Homefront game folder cannot use the TS2 Launcher creator option in the installer. Fails silently.

Windows shows "{path} unexpected at this time.

**Comment by GoTeamScotch** [comment]
Reported by Withered Rose in Discord. Still happens in v0.1.2
![launcher-error](https://user-images.githubusercontent.com/11036843/140668680-8919ee8b-c286-4997-adfa-bc4e3846cad7.png)
https://discord.com/channels/467580641639268362/833470927496806402/906615802571145247

**Comment by SandSkulker** [comment]
It's already mentioned in the Discord, but those who can't assess it, the workaround right now is to **make a copy of** **Homefront2_Release.exe** inside "steamapps\common\Homefront_The_Revolution\Bin64", paste it into the same location and rename the duplicate executable to **timesplitters2.exe**

The mod will still work as intended.

**Comment by GoTeamScotch** [comment]
Update: work is being done to replace the batch script with a new installer, which should make installation much easier and more stable. It's close to being done. There's two main features still being worked on: the Homefront ripper (reduce game size) and MD5-hash verification (to make sure your homefront EXE is compatible before installing).

People can follow the progress in the innosetup branch located here:
https://github.com/HFTSRedux/TS2Redux/tree/innosetup

Preview:
![image](https://user-images.githubusercontent.com/11036843/148194295-123f8dd0-f6cc-4eb0-81b4-ae510db35f13.png)

![image](https://user-images.githubusercontent.com/11036843/148194282-e3d1662b-ecfe-429b-b753-a85a24345a0c.png)

**Comment by GoTeamScotch** [comment]
Update: new version of the installer is now publicly available. Version 0.2.6 should fix issues like this when installing the mod. It uses an entirely new method of installing files than in previous versions. Please download and use the new version. Report any issues you encounter. Download: [TS2 Redux v0.2.6](https://github.com/HFTSRedux/TS2Redux/releases)

Marking this issue as closed. Feel free to reply if the problem persists.
