### ISSUE TITLE
"The system cannot find the path specified." When installing

### ISSUE THREAD

**Issue by kephalosmusic** [HFTSRedux/TS2Redux#9]
The bat file can't locate the folder when installing. 

D:\SteamLibrary\steamapps\common\Homefront_The_Revolution

That's the path its looking for and it is the correct path

**Comment by GoTeamScotch** [comment]
Which version are you using? Make sure you're using version [0.1.2](https://github.com/HFTSRedux/TS2Redux/releases/tag/v0.1.2).

Can you confirm that your game folder has the folder Bin64, and within that folder do you see Homefront2_Release.exe?

The code looks for `%gamepath%\Bin64\Homefront2_Release.exe`. If it can't find the EXE at your given game path, it asks you to try again. If you do have a game EXE at that path, then it makes me wonder if Windows is not reporting that to the script for some reason. You might try running the script as an Admin to rule out any Windows permissions issues.

You can also manually install the main mod files by copying the contents of the "App-DLLs" folder (found within [the ZIP download](https://github.com/HFTSRedux/TS2Redux/releases/tag/v0.1.2) for this project) to Homefront_The_Revolution\Bin64. 

_P.s. sorry for the delay. I didn't have notifications turned on._

**Comment by GoTeamScotch** [comment]
A new version of the installer has been released, version 0.2.6, which should fix issues like this when installing the mod. It uses an entirely new method of installing files than in previous versions. Please download and use the new version. Report any issues you encounter. Download: [TS2 Redux v0.2.6](https://github.com/HFTSRedux/TS2Redux/releases)

Marking this as closed. Feel free to reply if the problem persists.
